// <auto-generated />
using Asteh.Domain.DataProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asteh.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220311091927_CreatedUserDbs")]
    partial class CreatedUserDbs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Asteh.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("LastVisitDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_visit_date");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("UserLoginIndex")
                        .HasFilter("\"Login\" IS NOT NULL");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_users_type_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Asteh.Domain.Entities.UserTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AllowEdit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allow_edit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user_types");

                    b.ToTable("user_types", (string)null);
                });

            modelBuilder.Entity("Asteh.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("Asteh.Domain.Entities.UserTypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_types_type_id");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
